"""Write blob.c (next to this script): the shared pseudo-random const arrays the MCU benchmark reads tables and
weights from. Deterministic (seed 2026), so blob.c is generated rather than committed."""
from pathlib import Path

import numpy as np

rng = np.random.default_rng(2026)
N16, NF, N8 = 100_000, 36_000, 40_000
b16 = rng.integers(-32767, 32768, N16)
bf = rng.uniform(-0.1, 0.1, NF).astype(np.float32)
b8 = rng.integers(-127, 128, N8)


def arr(ctype, name, vals, fmt):
    rows = [", ".join(fmt(v) for v in vals[i:i + 16]) for i in range(0, len(vals), 16)]
    return f"const {ctype} {name}[{len(vals)}] = {{\n" + ",\n".join(rows) + "\n};\n"

with open(Path(__file__).with_name("blob.c"), "w") as f:
    f.write('#include "mcubench.h"\n/* generated by gen_blob.py (seed 2026) */\n')
    f.write(arr("int16_t", "BLOB16", b16, str))
    f.write(arr("float", "BLOBF", bf, lambda v: f"{float(v):.9g}f"))
    f.write(arr("int8_t", "BLOB8", b8, str))
    f.write(f"const size_t BLOB16_N = {N16}, BLOBF_N = {NF}, BLOB8_N = {N8};\n")
